
asset:
  idShort: "AAS_Sensor_Template"
  id: "urn:aas:ugv:sensor:demo:001"
  assetKind: "Instance"
  globalAssetId: "urn:asset:ugv:sensor:demo:001"
  thumbnail: null

general:
  manufacturerName: "Acme Robotics"
  productDesignation: "Ultrasonic Sensor A01A"


interface:
  base: "http://sensor.local/api"
  security: "nosec_sc"     # as per WoT security naming (NoSecurityScheme)
  forms:
    - href: "/distance"
      method: "GET"
      contentType: "application/json"
    - href: "/config"
      method: "PUT"
      contentType: "application/json"
