sensor:
  name: Ultrasonic_A01A
  manufacturer: DFRobot
  type: Ultrasonic
  datatype: double
  range: null            
  voltage: "5V"
  current: null
  reference: null


interface:
  protocol: "HTTP REST"
  endpoint: "http://192.168.1.100:8000/read"
  signal_path: "Vehicle.Chassis.Ultrasonic.Row1.Left.Distance"
  enable_publishing: true
